version: '3'
services:
  bot:
    build: ./bot
    links:
      - rethink
    depends_on:
      - rethink
    env_file: .env
  backend:
    build: ./web/backend
    links:
      - rethink
    depends_on:
      - rethink
    ports:
      - 3000:8080
    env_file: .env
  frontend:
    build: ./web/frontend
    ports:
      - 4000:8080
    env_file: .env
  rethink:
    image: rethinkdb:latest
    ports:
      - 5000:8080
