version: '3'
services:
  bot:
    build: .
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
