version: '3'
services:
  bot:
    build: .
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    env_file: .env
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
