version: '3'
services:
  bot:
    build: .
    links:
      - redis
      - postgres
  redis:
    image: redis:3.0-alpine
  web:
    build: https://github.com/spec-tacles/spectacles.git
    links:
      - redis
    ports:
      - 8080:8080
  postgres:
    image: postgres:9-alpine
