version: '2'
services:
  bot:
    build: ./bot
    depends_on:
      - postgres
    env_file: .env
    restart: always
    mem_limit: 8g
  postgres:
    image: postgres:9-alpine
    volumes:
      - /var/lib/postgresql/data
