version: '3'
services:
  pleb:
    build: .
    links:
      - redis
      - postgres
  redis:
    image: redis
  web:
    build: https://github.com/spec-tacles/spectacles.git
    links:
      - redis
    ports:
      - 8080:8080
  postgres:
    image: postgres
