server:
  port: 8080
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: youshallnotpass
    source:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: https://14a45e015b844139bbb922c6b04fc2a1:119e3e9312be4301a6dc524939d718ac@sentry.pleb.xyz/3

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavaink: INFO
